# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2016383c7b8061d32477a8fb257b2e681cfb1d651de1f3a48f69d67f24d8770b8bb37f52c052298616c4b51fe82219ac63d26be69cb4abdba5158c321dec4523

test:
  secret_key_base: cc830df43064547d09d5eb9ab4d1ffd738326a6736281374396fb6c0671c2a06b4b9663e26ffaa94d2fa944a7cb6074b7e2b95c46f84f3a1a800e3ca1f78e737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
